;海康威视巡检配置
[hkconfig]
;设备列表文件(CSV文件)
listPath=hklist.csv
;截图保存路径(末尾需加/)
picPath=image/
;PDF保存路径(末尾需加/)
pdfPath=pdf/
;报表保存路径
reportPath=report/
;公司名称
copy=中国网络信息技术有限公司  
;联系人
author=张三
;联系电话
phone=13666666666
;地址
addr=浙江省杭州市XX号 
;客户名
customer=浙江省XX科技有限公司