# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(440, 377)
        self.pushButton_query = QtWidgets.QPushButton(Form)
        self.pushButton_query.setGeometry(QtCore.QRect(70, 300, 75, 23))
        self.pushButton_query.setObjectName("pushButton_query")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(270, 300, 75, 23))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 421, 271))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 20, 171, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 71, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit_result = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_result.setGeometry(QtCore.QRect(30, 90, 371, 161))
        self.textEdit_result.setObjectName("textEdit_result")
        self.comboBox_w = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_w.setGeometry(QtCore.QRect(120, 50, 211, 22))
        self.comboBox_w.setObjectName("comboBox_w")
        self.comboBox_w.addItem("")
        self.comboBox_w.addItem("")
        self.comboBox_w.addItem("")

        self.retranslateUi(Form)
        # self.pushButton_query.clicked.connect(Form.query)
        # self.pushButton_clear.clicked.connect(Form.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Weather"))
        self.pushButton_query.setText(_translate("Form", "查询"))
        self.pushButton_clear.setText(_translate("Form", "清空"))
        self.label.setText(_translate("Form", "查询城市天气"))
        self.label_2.setText(_translate("Form", "城市"))
        self.comboBox_w.setItemText(0, _translate("Form", "北京"))
        self.comboBox_w.setItemText(1, _translate("Form", "上海"))
        self.comboBox_w.setItemText(2, _translate("Form", "广州"))
