# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guess.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(597, 538)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 50, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(200, 180, 171, 261))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_num = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_num.setMinimumSize(QtCore.QSize(100, 40))
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.verticalLayout.addWidget(self.lineEdit_num)
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.pushButton_confirm = QtWidgets.QPushButton(self.widget)
        self.pushButton_confirm.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.verticalLayout.addWidget(self.pushButton_confirm)
        self.pushButton_exit = QtWidgets.QPushButton(self.widget)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout.addWidget(self.pushButton_exit)
        self.pushButton_restart = QtWidgets.QPushButton(self.widget)
        self.pushButton_restart.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_restart.setObjectName("pushButton_restart")
        self.verticalLayout.addWidget(self.pushButton_restart)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Guess"))
        self.label.setText(_translate("Form", "猜  数  字"))
        self.pushButton_confirm.setText(_translate("Form", "确认"))
        self.pushButton_exit.setText(_translate("Form", "退出"))
        self.pushButton_restart.setText(_translate("Form", "重新开始"))
