[Settings]
# 占位符设置
NamePlaceholder = 某某
OrgPlaceholder = 某单位
LogoScanNum = 20

[WhiteList]
# 白名单，用英文逗号分隔
Items = 电磁兼容性,

[Replacements]
# <strong><font color="#FF0000">脱敏</font></strong>词汇替换规则 (原词 = 替换词)
大闸蟹 = DZX