# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conversion.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 201)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 240, 65))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_USD = QtWidgets.QLabel(self.centralwidget)
        self.label_USD.setGeometry(QtCore.QRect(206, 92, 63, 47))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(26)
        self.label_USD.setFont(font)
        self.label_USD.setObjectName("label_USD")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(275, 92, 113, 55))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(26)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_CNY = QtWidgets.QLabel(self.centralwidget)
        self.label_CNY.setGeometry(QtCore.QRect(590, 92, 66, 47))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(26)
        self.label_CNY.setFont(font)
        self.label_CNY.setObjectName("label_CNY")
        self.lineEdit_USD = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_USD.setGeometry(QtCore.QRect(20, 90, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(26)
        self.lineEdit_USD.setFont(font)
        self.lineEdit_USD.setObjectName("lineEdit_USD")
        self.lineEdit_CNY = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CNY.setGeometry(QtCore.QRect(390, 90, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(26)
        self.lineEdit_CNY.setFont(font)
        self.lineEdit_CNY.setObjectName("lineEdit_CNY")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conversion"))
        self.label.setText(_translate("MainWindow", "汇率转换器"))
        self.label_USD.setText(_translate("MainWindow", "USD"))
        self.pushButton.setText(_translate("MainWindow", "转换！"))
        self.label_CNY.setText(_translate("MainWindow", "CNY"))
