# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 131, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(181, 132, 133, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_min = QtWidgets.QLabel(self.centralwidget)
        self.label_min.setGeometry(QtCore.QRect(240, 170, 54, 12))
        self.label_min.setObjectName("label_min")
        self.label_max = QtWidgets.QLabel(self.centralwidget)
        self.label_max.setGeometry(QtCore.QRect(310, 170, 54, 12))
        self.label_max.setObjectName("label_max")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(430, 190, 75, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(150, 190, 227, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_shouYi = QtWidgets.QLabel(self.widget)
        self.label_shouYi.setObjectName("label_shouYi")
        self.horizontalLayout.addWidget(self.label_shouYi)
        self.doubleSpinBox_min = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_min.setObjectName("doubleSpinBox_min")
        self.horizontalLayout.addWidget(self.doubleSpinBox_min)
        self.doubleSpinBox_max = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_max.setObjectName("doubleSpinBox_max")
        self.horizontalLayout.addWidget(self.doubleSpinBox_max)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_min.setText(_translate("MainWindow", "最小值"))
        self.label_max.setText(_translate("MainWindow", "最大值"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.label_shouYi.setText(_translate("MainWindow", "收益"))
